Repository jetstack/test-infra, pull requests merged in 2018-07, with the labels that each got.

#213 Add cert-manager-chart-verify presubmit
  jobs/config.json
  prow/config.yaml
Labels: size/M

#215 Latest changes from upstream
  Gopkg.lock
  config/jobs/cadvisor/OWNERS
  config/jobs/cadvisor/cadvisor.yaml
  config/jobs/kubeflow/OWNERS
  config/jobs/kubeflow/kubeflow-periodics.yaml
  config/jobs/kubeflow/kubeflow-postsubmits.yaml
  config/jobs/kubeflow/kubeflow-presubmits.yaml
  config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml
  config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/OWNERS
  config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/gcp-filestore-csi-driver-config.yaml
  config/jobs/kubernetes/sig-node/OWNERS
  config/jobs/kubernetes/sig-node/node-kubelet.yaml
  config/jobs/kubernetes/test-infra/janitors.yaml
  config/jobs/kubernetes/test-infra/test-infra-periodics.yaml
  config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml
  config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml
  prow/config/config.go
  prow/config/config_test.go
  prow/config/jobs.go
  prow/config/jobs_test.go
  prow/gerrit/gerrit.go
  prow/pjutil/BUILD.bazel
  prow/pjutil/pjutil.go
  prow/pjutil/pjutil_test.go
  prow/plugins/label/label.go
  prow/plugins/label/label_test.go
  prow/plugins/trigger/trigger.go
  prow/plugins/verify-owners/verify-owners.go
  testgrid/cmd/configurator/config_test.go
  testgrid/config.yaml
Labels: size/XXL

#216 Bump hook to latest HEAD
  prow/cluster/hook_deployment.yaml
Labels: size/XS

#217 Remove duplicate tarmak presubmit
  prow/config.yaml
Labels: size/XS

#218 Enable job-config configmap and move cert-manager jobs
  config/jobs/cadvisor/OWNERS
  config/jobs/cadvisor/cadvisor.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/gke/gke-staging-gpu.yaml
  config/jobs/gke/gke-staging-upgrade.yaml
  config/jobs/gke/gke-staging.yaml
  config/jobs/kubeflow/OWNERS
  config/jobs/kubeflow/kubeflow-periodics.yaml
  config/jobs/kubeflow/kubeflow-postsubmits.yaml
  config/jobs/kubeflow/kubeflow-presubmits.yaml
  config/jobs/kubernetes-security/BUILD.bazel
  config/jobs/kubernetes-security/generated-security-jobs.yaml
  config/jobs/kubernetes-security/genjobs.go
  config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml
  config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/OWNERS
  config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml
  config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/OWNERS
  config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/gcp-filestore-csi-driver-config.yaml
  config/jobs/kubernetes/sig-node/OWNERS
  config/jobs/kubernetes/sig-node/node-kubelet.yaml
  config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml
  config/jobs/kubernetes/test-infra/janitors.yaml
  config/jobs/kubernetes/test-infra/test-infra-canaries.yaml
  config/jobs/kubernetes/test-infra/test-infra-periodics.yaml
  config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml
  config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.yaml
Labels: size/XXL

#219 Fix use of minikube-size preset labels
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  prow/config.yaml
Labels: size/M

#220 Copy across test-infra presubmits
  config/jobs/test-infra/test-infra-presubmits.yaml
Labels: size/L

#223 Add default plank decoration config
  prow/config.yaml
Labels: size/S

#225 Update tarmak's kubernetes versions to test against
  jobs/config.json
  prow/config.yaml
Labels: approved, lgtm, size/M
