Repository jetstack/test-infra, pull requests merged in 2018-06, with the labels that each got.

#200 Push docs for potential new tarmak releases
  prow/config.yaml
Labels: approved, lgtm

#201 Update plugins.yaml
  prow/plugins.yaml
Labels: size/XS

#202 Add JETSTACK.md
  prow/JETSTACK.md
Labels: size/M

#203 Enable automatic lifecycle periodics
  prow/config.yaml
Labels: approved, lgtm, size/M

#206 Use verify target for vault-unsealer instead of docker build
  jobs/config.json
Labels: approved, lgtm

#207 Update ruby image
  images/ruby/Dockerfile
  images/ruby/Makefile
  images/ruby/runner
  prow/config.yaml
Labels: approved, lgtm, size/S

#209 Update plugins.yaml
  prow/plugins.yaml
Labels: size/XS

#211 Bump dep to v0.4.1
  images/gcloud/Dockerfile
  images/gcloud/Makefile
Labels: size/XS
