Repository jetstack/test-infra, pull requests merged in 2018-08, with the labels that each got.

#228 Add jobs for ubuntu 1.11 and 1.10 and centos 1.11
  jobs/config.json
Labels: approved, lgtm, size/M

#226 Add metric scrape annotations and disable kube-lego
  prow/cluster/hook_service.yaml
  prow/cluster/lego_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/pushgateway_deployment.yaml
Labels: size/S

#230 Make cert-manager e2e jobs <k8s 1.9 non-blocking, and create periodics
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/M

#232 Bump helm version to 2.10-rc.3
  images/gcloud/Dockerfile
  images/gcloud/Makefile
  images/minikube-in-go/Dockerfile
  images/minikube-in-go/Makefile
Labels: size/XS

#233 Bump cert-manager test images
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/S

#239 Set GOPATH on cert-manager bazelbuild
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: ¯\_(ツ)_/¯

#240 Bump bazel version in minikube-in-go
  images/minikube-in-go/Makefile
Labels: size/XS

#241 Bump minikube-in-go for cert-manager e2e jobs
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/S

#249 Add test cert-manager decorated job and image
  config/images/cert-manager/golang/Dockerfile
  config/images/cert-manager/golang/Makefile
  config/jobs/cert-manager/cert-manager-canaries.yaml
Labels: dco-signoff: yes, size/M

#250 Remove pr_verify target
  config/jobs/cert-manager/cert-manager-canaries.yaml
Labels: dco-signoff: no

#251 Disable dco bot for cert-manager
  prow/plugins.yaml
Labels: dco-signoff: no, size/XS

#252 Use gcr.io decoration images
  prow/config.yaml
Labels: dco-signoff: yes, size/XS
