Repository jetstack/test-infra, pull requests merged in 2018-05, with the labels that each got.

#181 Configure bazel remote caching
  images/bootstrap/create_bazel_cache_rcs.sh
  prow/config.yaml
Labels: size/S

#182 Fix naming of triggers for vault_client/etcd
  prow/config.yaml
Labels: approved, lgtm, size/XS

#183 Add experimental dind based cert-manager verify presubmit
  .bazelrc
  images/bootstrap/Makefile
  images/bootstrap/runner
  images/cert-manager-test/Dockerfile-0.3
  images/cert-manager-test/Makefile
  images/cert-manager-test/README.md
  jobs/config.json
  prow/config.yaml
  scenarios/cert-manager_verify.py
Labels: size/L

#188 Update subnets to not overlap with any existing resources
  dind/start.sh
Labels: size/S

#189 Add quick-verify job for vault-plugin-auth-templated-aws
  jobs/config.json
  prow/config.yaml
Labels: approved, lgtm, size/M

#190 Enable plugins for vault-plugin-auth-templated-aws
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#191 Add verify and acceptance tests for fluent-bit and aws_es_proxy
  jobs/config.json
  prow/config.yaml
Labels: approved, lgtm, size/M

#196 Add okta-kubectl-auth
  jobs/config.json
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#198 Ensure run if changed has always run false
  prow/config.yaml
Labels: approved, lgtm, size/S
