Repository jetstack/test-infra, pull requests merged in 2018-04, with the labels that each got.

#168 Add puppet tarmak module test for main tarmak repo
  jobs/config.json
  prow/config.yaml
Labels: size/M

#170 Run puppet modules tarmak for different versions
  jobs/config.json
  prow/config.yaml
Labels: size/L

#173 Enable skip plugin
  prow/plugins.yaml
Labels: size/XS

#174 Add verify job for vault-helper and -unsealer
  jobs/config.json
  prow/config.yaml
Labels: approved, lgtm, size/M

#178 cert-manager: skip e2e tests when only files in docs/ have changed
  prow/config.yaml
Labels: size/S

#179 Enable persistent local volumes
  scenarios/minikube.py
Labels: approved, lgtm, size/XS
