Repository jetstack/test-infra, pull requests merged in 2018-03, with the labels that each got.

#147 Install vert and yaml, and bump Helm version to 2.8.1
  images/gcloud/Dockerfile
  images/gcloud/Makefile
Labels: size/S

#148 Update cert-manager-quick-verify to gcloud-in-go 0.9
  prow/config.yaml
Labels: size/XS

#152 Run periodic job to retest approved PRs on navigator
  prow/config.yaml
Labels: size/L

#149 Enable lifecycle plugin for cert-manager
  prow/plugins.yaml
Labels: size/XS

#154 Only request a review from 1 reviewer
  prow/plugins.yaml
Labels: size/XS

#156 Switch cert-manager to use tide
  mungegithub/submit-queue/deployment/cert-manager/Makefile
  mungegithub/submit-queue/deployment/cert-manager/configmap.yaml
  mungegithub/submit-queue/ingress.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#157 Run retest bot on PRs that haven't been updated >30m
  prow/config.yaml
Labels: size/XS

#158 jobs/cert-manager: add 'verify_pr' to verify
  jobs/config.json
Labels: approved, lgtm, size/XS

#153 Use job presets for svc acct, libvirt and minikube
  prow/config.yaml
Labels: size/L

#159 Add Bazel jobs for Navigator
  images/bazelbuild/Makefile
  images/bazelbuild/runner
  images/minikube-in-go/Dockerfile
  images/minikube-in-go/Makefile
  prow/config.yaml
Labels: size/L

#161 Fix minikube job resource requests
  prow/config.yaml
Labels: size/S

#162 Add Kubernetes 1.10.0 image & bump k8s patch versions
  images/minikube-in-go/Makefile
Labels: size/XS

#163 Bump Kubernetes patch versions and add 1.10 e2e test
  jobs/config.json
  prow/config.yaml
Labels: size/M

#164 Disable 1.10 e2e jobs running by default
  prow/config.yaml
Labels: size/XS

#165 Test run_if_changed feature of plank
  jobs/config.json
  prow/config.yaml
Labels: size/M
